#This is the makefile of EpollTest

.PHONY:all
all:epoll_server epoll_client
epoll_server:
	gcc epoll_server.c -o epoll_server
epoll_client:
	gcc epoll_client.c -o epoll_client
clean:
	rm -f epoll_server epoll_client
